export const LoaderConfig = {
    bg: require("../../../sprites/bg.png"),
    symbol_0: require("../../../sprites/BONUS.png"),
    symbol_1: require("../../../sprites/H1.png"),
    symbol_2: require("../../../sprites/H2.png"),
    symbol_3: require("../../../sprites/H3.png"),
    symbol_4: require("../../../sprites/H4.png"),
    symbol_5: require("../../../sprites/H5.png"),
    symbol_6: require("../../../sprites/H6.png"),
    symbol_7: require("../../../sprites/M1.png"),
    symbol_8: require("../../../sprites/M2.png"),
    symbol_9: require("../../../sprites/M3.png"),
    symbol_10: require("../../../sprites/M4.png"),
    symbol_11: require("../../../sprites/M5.png"),
    symbol_12: require("../../../sprites/M6.png"),
    symbol_13: require("../../../sprites/A.png"),
    symbol_14: require("../../../sprites/K.png"),
    symbol_15: require("../../../sprites/Q.png"),
    symbol_16: require("../../../sprites/J.png"),
    symbol_17: require("../../../sprites/10.png"),
    symbol_18: require("../../../sprites/9.png"),
    indicator: require("../../../sprites/indicator.png"),
    spin_Button: require("../../../sprites/spin_button.png"),

};